CREATE TABLE CATEGORY(
CATCODE VARCHAR(3) PRIMARY KEY,
CATDESC VARCHAR2(11)NOT NULL);
COMMIT;
INSERT INTO CATEGORY
VALUES('BUS','BUSINESS');
INSERT INTO CATEGORY
VALUES('CHN','CHILDREN');
INSERT INTO CATEGORY
VALUES('COK','COOKING');
INSERT INTO CATEGORY
VALUES('COM','COMPUTER');
INSERT INTO CATEGORY
VALUES('FAL','FAMILY LIFE');
INSERT INTO CATEGORY
VALUES('FIT','FITNESS');
INSERT INTO CATEGORY
VALUES('SEH','SELF HELP');
INSERT INTO CATEGORY
VALUES('LIT','LITERATURE');
COMMIT;
ALTER TABLE BOOKS
ADD CATCODE VARCHAR(3);
COMMIT;
ALTER TABLE BOOKS
ADD FOREIGN KEY (CATCODE) REFERENCES CATEGORY(CATCODE);
COMMIT;
UPDATE BOOKS
SET CATCODE = 'FIT'
WHERE CATEGORY='FITNESS';
UPDATE BOOKS
SET CATCODE = 'FAL'
WHERE CATEGORY='FAMILY LIFE';
UPDATE BOOKS
SET CATCODE = 'CHN'
WHERE CATEGORY='CHILDREN';
UPDATE BOOKS
SET CATCODE = 'COM'
WHERE CATEGORY='COMPUTER';
UPDATE BOOKS
SET CATCODE = 'COK'
WHERE CATEGORY='COOKING';
UPDATE BOOKS
SET CATCODE = 'SEH'
WHERE CATEGORY='SELF HELP';
UPDATE BOOKS
SET CATCODE = 'BUS'
WHERE CATEGORY = 'BUSINESS';
UPDATE BOOKS
SET CATCODE = 'LIT'
WHERE CATEGORY='LITERATURE';
SHOW TABLES;
COMMIT;
ALTER TABLE BOOKS
DROP COLUMN CATEGORY;
COMMIT;
